export const RECENT_ACTIVITIES = 'RECENT_ACTIVITES';
export const SELECTED_CAMERA_DEVICE_ID = 'SELECTED_CAMERA_DEVICE_ID';
export const SELECTED_MIC_DEVICE_ID = 'SELECTED_MIC_DEVICE_ID';
export const SELECTED_SPEAKER_DEVICE_ID = 'SELECTED_SPEAKER_DEVICE_ID';